#!/usr/bin/env python3
# (c) 2014 jano <janoh@ksp.sk>
# Script that helps generating inputs for contests
description = '''
Input generator.
Generate inputs based on input description file. Each line is provided as input to
generator. Empty lines separate batches.
'''
options = [
    'indir', 'inext',
    'compile', 'execute', 'gencmd',
    'colorful', 'quiet',
    'clearinput', 'clearbin',
    'description',
]

from input_tool.common.parser import Parser
from input_tool.common.recipes import Recipe
from input_tool.common.commands import Generator
from input_tool.common.messages import *
import atexit
import os
import sys

parser = Parser(description, options)
args = parser.parse()
Color.setup(args)

if args.description:
    recipe = Recipe(open(args.description, 'r'))
else:
    recipe = Recipe(sys.stdin)

recipe.process()
programs = {x:Generator(x,args) for x in recipe.programs}

# {{{ ----------- prepare programs -------------------
gencmd = args.gencmd
programs[gencmd] = Generator(gencmd, args)

def cleanup():
    if args.clearbin:
        for p in programs:
            programs[p].clear_files()
atexit.register(cleanup)

for p in sorted(programs):
    programs[p].prepare()
# }}}

indir = args.indir
if not os.path.exists(indir):
    infob("Creating directory '%s'" % indir)
    os.makedirs(indir)

filestoclear = os.listdir(indir)
if len(filestoclear) and args.clearinput:
    infob("Cleaning directory '%s:'" % indir)
    # delete only following files
    exttodel = ['in', 'out', 'temp', args.inext]
    for file in filestoclear:
        if file.endswith(args.inext) and 'sample' in file:
            info("  ommiting file '%s'" % file)
        elif file.rsplit('.',1)[-1] not in exttodel:
            info("  not deleting file '%s'" % file)
        else:
            os.remove('%s/%s' % (indir, file))


infob('Generating:')
recipe.inputs.sort()
leftw = max([len(i.get_name(ext=args.inext)) for i in recipe.inputs])
prev = None

for input in recipe.inputs:
    ifile = input.get_name(path=indir + '/', ext=args.inext)
    short = ('{:>' + str(leftw) + 's}').format(input.get_name(ext=args.inext))

    status = programs[input.generator or gencmd].generate(
        ifile,
        input.get_generation_text(),
    )

    if prev and prev.batch != input.batch:
        print(' ' * (leftw + 4) + '.')
    prev = input

    msg = '  %s  <  %s' % (short, input.get_info_text(len(short)+4))
    if status != Status.ok:
        msg += '\t!Generator encountered an error!'
    print(Color.colorize(status, msg))

infob('Done')
